name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tampilkan isi repo
        run: ls -lah

      - name: Print pesan sukses
        run: echo "✅ Workflow GitHub Actions berhasil jalan!"
